# Generated by Django 3.1.2 on 2020-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(help_text='Latitude for squirrel')),
                ('Longitude', models.FloatField(help_text='Longitude for squirrel')),
                ('Unique_Squirrel_ID', models.CharField(help_text='Identification tag for each squirrel sightings', max_length=100)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Morning or evening', max_length=100)),
                ('Date', models.CharField(blank=True, max_length=100)),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), (None, ''), ('?', '?')], help_text='Age of squirrel', max_length=100)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), (None, '')], help_text='Primary fur color of squirrel', max_length=100)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), (None, '')], help_text='Location of squirrel', max_length=100)),
                ('Specific_Location', models.CharField(blank=True, help_text='Specific location of squirrel', max_length=100)),
                ('Running', models.BooleanField(blank=True, help_text='Whether or not squirrel is running')),
                ('Chasing', models.BooleanField(blank=True, help_text='Whether or not squirrel is chasing')),
                ('Climbing', models.BooleanField(blank=True, help_text='Whether or not squirrel is climbing')),
                ('Eating', models.BooleanField(blank=True, help_text='Whether or not squirrel is eating')),
                ('Foraging', models.BooleanField(blank=True, help_text='Whether or not squirrel is foraging')),
                ('Other_Activities', models.CharField(blank=True, help_text='Other activities of squirrel', max_length=100)),
                ('Kuks', models.BooleanField(blank=True, help_text='Whether or not squirrel kuks')),
                ('Quaas', models.BooleanField(blank=True, help_text='Whether or not squirrel quaas')),
                ('Moans', models.BooleanField(blank=True, help_text='Whether or not squirrel moans')),
                ('Tail_Flags', models.BooleanField(blank=True, help_text='Whether or not squirrel tail flags')),
                ('Tail_Twitches', models.BooleanField(blank=True, help_text='Whether or not squirrel tail twitches')),
                ('Approaches', models.BooleanField(blank=True, help_text='Whether or not squirrel approaches')),
                ('Indifferent', models.BooleanField(blank=True, help_text='Whether or not squirrel is indifferent')),
                ('Runs_From', models.BooleanField(blank=True, help_text='Whether or not squirrel runs from')),
            ],
        ),
    ]
