# Generated by Django 3.0.7 on 2020-10-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201011_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Identification tag for each squirrel sightings', max_length=100, primary_key=True, serialize=False),
        ),
    ]
