# Generated by Django 3.0.7 on 2020-10-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20201015_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
